// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjaiGK4iTXFn-J1FhujrH_8BU5dEgiUI',
    appId: '1:583801780443:web:ec970f490ec0e08b7834fe',
    messagingSenderId: '583801780443',
    projectId: 'twitter-copycat',
    authDomain: 'twitter-copycat.firebaseapp.com',
    storageBucket: 'twitter-copycat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmTWPZ7ts2lDygVnIJEaU2Y_x7ZIP7OU',
    appId: '1:583801780443:android:dd59e9e0a9cb7ea27834fe',
    messagingSenderId: '583801780443',
    projectId: 'twitter-copycat',
    storageBucket: 'twitter-copycat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKF-S0V9xkbQiXX2Df00-KTgG6RvVnQm8',
    appId: '1:583801780443:ios:325400ba0f4fcea77834fe',
    messagingSenderId: '583801780443',
    projectId: 'twitter-copycat',
    storageBucket: 'twitter-copycat.appspot.com',
    iosClientId: '583801780443-pfflja1mdpn0he99485e2khi0p846eu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterCopycat',
  );
}
